name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go install github.com/yusufcanb/tlm

      - name: Build
        run: bash build.sh $(cat VERSION)

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('e2e/requirements.txt') }}

      - name: Install tlm
        run: |
          mv $(cat VERSION)/tlm_$(cat VERSION)_linux_amd64 /usr/local/bin/tlm 
          chmod +x /usr/local/bin/tlm
          tlm help

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r e2e/requirements.txt

      - name: Run Tests wo/ Ollama
        run: robot --outputdir dist --name tlm --include no-ollama tests/
        working-directory: e2e/

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-report
          path: e2e/dist/

    needs:
      - build
